name: ci

on:
  push:
    paths-ignore:
      - '**.rst'
      - LICENSE
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]

jobs:
  build-checks:
    runs-on: ubuntu-latest
    container: 'alpine:3.20'

    steps:
      - uses: actions/checkout@v2

      - id: install_deps
        run: |
          apk update
          apk add python3 black

      - id: linter
        run: |
          black --check --diff --color mupub/
